name: Nginx Docker Image CI

on:
  push:
    paths:
      - 'nginx/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd nginx && docker build . --file Dockerfile --tag johnpoint/nginx:$(date +%s)
    
    - name: Login to DockerHub
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push to DockerHub
      run: |
        - docker push johnpoint/nginx:$(date +%s)
        - docker tag johnpoint/nginx:$(date +%s) johnpoint/nginx:lastest
        - docker push johnpoint/nginx:lastest
